<a href="https://colab.research.google.com/github/kurianshaji17-create/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python

#array collection of data with same datatype (homogenious)

a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
import numpy as np #numerical python

#array collection of data with same datatype (homogenious)

a=np.array([1,2,3,4,"a"])
print(a)


['1' '2' '3' '4' 'a']


In [ ]:
#slicing forward and backward slicing

b=np.array([1,2,3,4,5])

#print 1,2
#print 5,4
#print 4,5
#print 2,1


In [ ]:
#slicing forward slicing backward slicing

b=np.array([1,2,3,4,5])
#print[1 2]
print(b[0:2])
#print[4 5]
print(b[3:5])
#print[2 1]
print(b[1::-1])
#print[5 4]
print(b[-1:-3:-1])

In [ ]:
#dimension
a=np.array([0,2,3,4,5])
b=np.array([[1,2],[3,4],[5,6]])

a.ndim #dimension=1 vector

b.ndim #dimension=2 matrix
print(a)
print(b)

b.shape

In [ ]:
#create a 2x2 matrix [2,3],[4,5]

d=np.array([[2,3],[4,5]])
print(d)
print(d.shape)
print(d.ndim) #dimention
print(d.size)

In [ ]:
#create a 2x3 matrix and print ,size,shape ,dimension
d=np.array([[2,3,4],[5,6,7]])
print(d)
print(d.size)
print(d.shape)
print(d.ndim)

In [ ]:
#create 4x2 matrix display its size shape and dimension

d=np.array([[1,2],[3,4],[5,6],[7,8]])
print(d.size)
print(d.shape)
print(d.ndim)
print(d)

8
(4, 2)
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#create 4x4 matrix display its size shape and dimension

import numpy as np

d=np.array([[1,2,3,4],[3,4,6,7],[5,6,8,6],[7,8,6,4]])
print(d.size)
print(d.shape)
print(d.ndim)
print(d)

16
(4, 4)
2
[[1 2 3 4]
 [3 4 6 7]
 [5 6 8 6]
 [7 8 6 4]]


19-09-25


In [ ]:
d [0]
d[:,0]
d[1,1]
d[2,2]
d[3,2:]
d[2:,2:]

array([[8, 6],
       [6, 4]])

In [ ]:
#zero matrix

z=np.zeros([3,3,3])
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#create two 2x2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition
print(a+b)

#matrix substraction
print(a-b)

#matrix multiplication
print(a*b)

[[ 4  3]
 [ 9 11]]
[[-2  1]
 [-3 -3]]
[[ 3  2]
 [18 28]]


In [ ]:
#full matrix

z=np.full([3,3],5,dtype=int)
z

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#identity matrix

z=np.identity(3,dtype=int)
z
z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create a 4x4 matrix

y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12,],[13,14,15,16]])
print(y)
print(y.size)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [ ]:
a=y.reshape(16,1)
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [ ]:
#create 8x2 matrix
a=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
print(a)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
#arange
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange
z=np.arange(1,11).reshape(5,2)
z

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#floor
z=np.floor(a)
z

array([1., 3., 5., 7., 9.])

In [ ]:
#ceil
z=np.ceil(a)
z


array([1., 3., 5., 7., 9.])

In [ ]:
#round
z=np.round(a)
z

array([1, 3, 5, 7, 9])

In [ ]:
#create a 3x3 matrix
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.max())#to find the maximum element in the entire metrix
print(a.max(axis=1))#to find the maximum element in the row
print(a.max(axis=0))#to find the maximum element in the coloumn


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
[7 8 9]


In [3]:
 #sum


 #print(p)
 #print(p.sum())
 #print(p.sum(axis=1))    #to find sum of each row
 #print(p.sum(axis=0))    #to find sum of each coloumn


#print(np.sqrt(p))        #to get squareroot
#print(np.sin(p))         #to get the sin
#print(np.cos(p))
 print(np.tan(p))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [4]:
 #sum

import numpy as np
s=np.array(([3,4,1],[5,3,1],[6,9,8]))
 #print(p)
 #print(p.sum())
 #print(p.sum(axis=1))    #to find sum of each row
 #print(p.sum(axis=0))    #to find sum of each coloumn


#print(np.sqrt(p))        #to get squareroot
#print(np.sin(p))         #to get the sin
#print(np.cos(p))
 print(np.tan(p))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [7]:
#FLATTEN

#create 3x3 matrix

import numpy as np
s=np.array(([3,4,1],[5,3,1],[6,9,8]))
#print(s)
#b=np.sort(s,axis=0)     #metod used for sorting
b=np.sort(s,axis=1)      #used to sort the row
print(b)



[[1 3 4]
 [1 3 5]
 [6 8 9]]


In [9]:
#SORT

#create 3x3 matrix

import numpy as np
s=np.array(([3,4,1],[5,3,1],[6,9,8]))
#print(s)
#b=np.sort(s,axis=0)    #method used for sorting in the coloumn
#b=np.sort(s,axis=1)    #used to sort the row
#print=b

#AR sorting

c=np.argsort(s,axis=1)    #sorting on the basis of indexing no. in the o/p we get the matrix and index no.
print(c)

[[2 0 1]
 [2 1 0]
 [0 2 1]]
